issue_category_map = {
    "pothole": "public",
    "road_damage": "public",
    "broken_streetlight": "public",
    "graffiti": "public",
    "garbage": "public",
    "vandalism": "public",
    "open_drain": "public",
    "blocked_drain": "public",
    "flood": "public_and_business",
    "fire": "public_and_business",
    "illegal_construction": "public",
    "tree_fallen": "public",
    "public_toilet_issue": "public",
    "stray_animals": "public",
    "noise_pollution": "public",
    "air_pollution": "public",
    "water_leakage": "public",
    "street_vendor_encroachment": "public",
    "signal_malfunction": "public",
    "waterlogging": "public",
    "property_damage": "business",
    "structural_damage": "business",
    "furniture_damage": "business",
    "home_repair": "business",
    "plumbing_issue": "business",
    "electrical_issue": "business",
    "ac_not_working": "business",
    "cctv_issue": "business",
    "internet_issue": "business",
    "water_purifier_issue": "business",
    "paint_damage": "business",
    "ceiling_leakage": "business",
    "door_lock_issue": "business",
    "appliance_malfunction": "business",
    "other": "public_and_business",
    "unknown": "public"
}

issue_department_map = {
    "fire": "Fire Department",
    "pothole": "Public Works Department",
    "garbage": "Sanitation Department",
    "property_damage": "Property Management Department",
    "flood": "Emergency Services Department",
    "vandalism": "Police Department",
    "structural_damage": "Building Inspection Department",
    "unknown": "City Department"
}